services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: champion-app:dev
    container_name: champion-app
    environment:
      APP_ENV: local
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: champion-nginx
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - internal
      - public

  mysql:
    image: mysql:8.0
    container_name: champion-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-sail}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    command: ["mysqld","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: champion-redis
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal

networks:
  internal: {}
  public: {}

volumes:
  mysql-data: {}
  redis-data: {}