version: "3.9"

x-env: &env
  env_file:
    - .env.docker

services:
  nginx:
    image: nginx:alpine
    <<: *env
    ports:
      - "${APP_HTTP_PORT:-8080}:80"
    volumes:
      - app-storage:/var/www/html/storage
      - app-public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - echo
    networks:
      - internal
      - public

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: champion-app:latest
    <<: *env
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
    volumes:
      - app-storage:/var/www/html/storage
      - app-public:/var/www/html/public
    depends_on:
      - mysql
      - redis
    networks:
      - internal

  queue:
    image: champion-app:latest
    <<: *env
    command: php artisan queue:work --tries=3 --sleep=1 --timeout=180
    volumes:
      - app-storage:/var/www/html/storage
      - app-public:/var/www/html/public
    depends_on:
      - app
      - redis
      - mysql
    networks:
      - internal

  schedule:
    image: champion-app:latest
    <<: *env
    command: php artisan schedule:work
    volumes:
      - app-storage:/var/www/html/storage
      - app-public:/var/www/html/public
    depends_on:
      - app
    networks:
      - internal

  echo:
    image: node:18-alpine
    <<: *env
    working_dir: /srv/echo
    command: sh -c "npm i -g laravel-echo-server && laravel-echo-server start --force --config=/srv/echo/laravel-echo-server.json"
    ports:
      - "${WS_PORT:-6001}:6001"
    volumes:
      - ./docker/echo/laravel-echo-server.json:/srv/echo/laravel-echo-server.json:ro
    depends_on:
      - redis
      - app
    networks:
      - internal

  mysql:
    image: mysql:8.0
    <<: *env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

  redis:
    image: redis:7-alpine
    <<: *env
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal

networks:
  internal:
  public:

volumes:
  mysql-data:
  redis-data:
  app-storage:
  app-public: